version: '3'

networks:
  db-network:
    driver: bridge

services:
  db:
    image: mongo
    networks:
      - db-network
    container_name: mongodb
    volumes:
      - /mnt/d/env/docker/volumes/mongodb:/data/db
    ports:
      - "27017:27017"

  website:
    build: ./packages/website
    ports:
      - "3000:3000"
    networks:
      - db-network
    depends_on:
      - server

  server:
    build: ./packages/server
    ports:
      - "3105:3105"
    networks:
      - db-network
    depends_on:
      - db