version: '3'

networks:
  base:
    driver: bridge

services:
  db:
    image: mongo
    networks:
      - base
    container_name: mongodb
    volumes:
      - ${MONGODB_DATA_PATH}:/data/db

  website:
    build: ./packages/website
    container_name: website-web
    networks:
      - base
    depends_on:
      - server

  server:
    build: ./packages/server
    container_name: website-server
    # secrets:
    #   - website-server
    networks:
      - base
    depends_on:
      - db

  nginx:
    build: ./packages/nginx
    ports:
      - "80:80"
    networks:
      - base